### PR TITLE
fix: store a/c info only when creds are valid

### LINKED ISSUE #100: Revoked Access Token - No longer can set new access token up
Per the title

I set a access token and during my troubleshooting I revoked it (as it wouldn't connect, did know about allow_local_remote_servers).

The page on trying to set up a new access token for Gitlab Integration in Personal Settings is now gone! Vanished!

`TypeError: n is null
    m index.mjs:133
    m index.mjs:126
    Underscore 3
        be
        n
        k
    formatAccountForSelect PersonalSettings.vue:223
    selectedAccount PersonalSettings.vue:201
    VueJS 3
        get
        evaluate
        Na
    Q PersonalSettings.vue:5
    VueJS 18
        _render
        a
        get
        e
        mount
        $mount
        init
        v
        v
        Pr
        _update
        a
        get
        e
        mount
        $mount
        _init
        Ra
    <anonymous> personalSettings.js:22
    <anonymous> personalSettings.js:24
    <anonymous> personalSettings.js:24
[vue.runtime.esm.js:3065:16](webpack:///integration_gitlab/node_modules/vue/dist/vue.runtime.esm.js)
    VueJS 21
        dn
        un
        ln
        _render
        a
        get
        e
        mount
        $mount
        init
        v
        v
        Pr
        _update
        a
        get
        e
        mount
        $mount
        _init
        Ra
    <anonymous> personalSettings.js:22
    <anonymous> personalSettings.js:24
    <anonymous> personalSettings.js:24`
    
  
fe2f0c41-9adb-48cf-84ce-69b8d4ba962c

System Info:
NC 29.0.5
Gitlab Integration 3.1.1
TrueNAS 23.04 (can't imagine a world this is the cause)

### PR DESCRIPTION
**Pull request by kyteinsky**
and better error handling

fixes #100

### CODE REVIEW

File: lib/Controller/ConfigController.php [hunk 1]
```diff
@@ -231,12 +247,22 @@ public function oauthRedirect(string $code = '', string $state = ''): RedirectRe
 		);
 	}
 
-	private function storeUserInfo(GitlabAccount $account): void {
+	/**
+	 * @param GitlabAccount $account
```
Comment (provokateurin) [inline lib/Controller/ConfigController.php:251]:
```suggestion
```
Not necessary as the type is already specified

File: lib/Controller/ConfigController.php [hunk 2]
```diff
@@ -231,12 +247,22 @@ public function oauthRedirect(string $code = '', string $state = ''): RedirectRe
...
 		$info = $this->gitlabAPIService->request($account, $account->getUrl(), 'user');
-		if (isset($info['username']) && isset($info['id'])) {
-			$account->setUserInfoName($info['username']);
-			$account->setUserInfoDisplayName($info['name']);
-			$this->accountMapper->update($account);
+		if (isset($info['error'])) {
+			throw new Exception($info['error'], $info['code'] ?? 500);
+		}
+		if (!isset($info['username'])) {
+			throw new Exception('Invalid response from Gitlab API, missing username', 500);
```
Comment (provokateurin) [inline lib/Controller/ConfigController.php:261]: Please throw some OCS*Exception instead

File: lib/Controller/ConfigController.php (hunk 1 above)
Comment (kyteinsky) [reply lib/Controller/ConfigController.php:251]: it was just the autocomplete, doesn't harm though, right?

File: lib/Controller/ConfigController.php (hunk 2 above)
Comment (kyteinsky) [reply lib/Controller/ConfigController.php:261]: you mean sub-classed exceptions? The controller is not for OCS.

File: lib/Controller/ConfigController.php (hunk 1 above)
Comment (provokateurin) [reply lib/Controller/ConfigController.php:251]: Not really, but it's cleaner to skip it as otherwise the two type definitions could drift apart.

File: lib/Controller/ConfigController.php (hunk 2 above)
Comment (provokateurin) [reply lib/Controller/ConfigController.php:261]: Hm ok

File: lib/Controller/ConfigController.php (hunk 1 above)
Comment (kyteinsky) [reply lib/Controller/ConfigController.php:251]: psalm would warn us if we do that. Also, it seems better to just mention all of them instead of selective params, no? Could be better for some IDEs too.

**Review by provokateurin — APPROVED** [review]
